site_name: Nexus Data Store Documentation
site_url: https://thenexusavenger.github.io/Nexus-Data-Store
repo_name: TheNexusAvenger/Nexus-Data-Store
repo_url: https://github.com/TheNexusAvenger/Nexus-Data-Store

theme:
  name: 'material'
  palette:
    primary: 'Blue'
    accent: 'Light Blue'

nav:
  - Home: index.md
  - Using Nexus Data Store: using-nexus-data-store.md
  - API Reference: api-reference.md
  - Communication Overview: communication-overview.md

markdown_extensions:
  - admonition
  - codehilite